### ISSUE TITLE
Oracle connect fail

### ISSUE THREAD

**Issue by rd5802** [pbugnion/jupyterlab-sql#81] opened 2019-06-24 13:38 UTC
While trying to connect to Oracle database by:
oracle://user:passwd@host:1521/service_name

I get the following message:
"Failed to reach server endpoints. Is the server extension installed correctly?"

Where to start solving this problem?

**Comment by pbugnion** [comment] 2019-06-24 18:14
Have you enabled the server extension? You can use `jupyter serverextension list` to get a list of server extensions currently active. It should look like this:

<img width="464" alt="Screenshot 2019-06-24 at 19 14 22" src="https://user-images.githubusercontent.com/1392879/60041878-4f496300-96b4-11e9-9870-4856d9297c0c.png">

**Comment by rd5802** [comment] 2019-06-25 10:15
Server extension is not enabled, but lab extension is enabled.
What shoud i do next?

![image](https://user-images.githubusercontent.com/35902744/60090413-caf1f100-9742-11e9-9a35-14ac54016312.png)

**Comment by pbugnion** [comment] 2019-06-25 20:13
Did you run `jupyter serverextension enable jupyterlab_sql --py --sys-prefix` to enable the server extension?

**Comment by pbugnion** [comment] 2019-06-25 20:13
(also, I'd recommend updating `jupyterlab-sql` to `0.2.1` with `pip install -U jupyterlab-sql.

**Comment by rd5802** [comment] 2019-06-26 09:34
We install through npm repo. https://www.npmjs.com/package/jupyterlab-sql is still in 1.9 version.

**Comment by rd5802** [comment] 2019-06-26 12:57
Managed to connect and run query, but jupyter-sql seems not to have visible option to kill database session. 
Since Oracle cluster I connect has SESSIONS_PER_USER limit = 1, I can`t run another one, the last resort option is to kill & restart jupyter server.



(cx_Oracle.DatabaseError) ORA-02391: exceeded simultaneous SESSIONS_PER_USER limit (Background on this error at: http://sqlalche.me/e/4xp6)

**Comment by pbugnion** [comment] 2019-06-26 17:55
> We install through npm repo

I'm a bit confused -- the installation instructions suggest you use pip:

```
pip install jupyterlab_sql
jupyter serverextension enable jupyterlab_sql --py --sys-prefix
jupyter lab build
```

See the README for details on installation.

**Comment by pbugnion** [comment] 2019-06-26 19:48
> but jupyter-sql seems not to have visible option to kill database session.

The session's lifetime is that of the query -- for all database engines apart from sqlite, the session should get terminated when the SQL command finishes.

Did you run a single command that takes a long time to execute, and then try to run other commands at the same time?

**Comment by rd5802** [comment] 2019-06-27 10:44
The instructons were followed.
npm repo is not consistent with github repo.  Our internal artifactory repo pulls from secure sources.

**Comment by pbugnion** [comment] 2019-07-14 20:51
@rd5802 The NPM package is a spoof (see issue #89 ). It does not install the server extension.

I'm not sure what you installed, but I strongly recommend installing packages from Pypi (or pointing your internal artifactory repo to Pypi for jupyterlab-sql). That's the only package that I maintain.

**Comment by pbugnion** [comment] 2019-07-14 20:51
Closing this as not directly related to Oracle. I think this is just a duplicate of issue #89.

Feel free to re-open if you think I assessed this incorrectly.

**Closed by pbugnion** 2019-07-14 20:51 UTC
